### PR TITLE
Feature/activites home

### PR DESCRIPTION
**Pull request by jamesaspence**
I believe we'll need to update the images used here. The styling is going to need some work, I believe - there's probably a simpler way to do what I'm doing.

Feel free to review the changes and add comments / suggestions.

### CODE REVIEW

**Comment by theosyslack** [comment]
Can you explain why we need to have the Cards doing all that width math?

**Comment by jamesaspence** [comment]
We do all the calculations within the card so we can specify a single prop on the card, `size`, that determines if it's full or half size. I assume these cards will not be many other sizes, so I put that within the class itself. Please check out the implementation, I can add some JSDoc to help clarify as well.

**Comment by theosyslack** [comment]
I guess my question is more why do we need it? What is this accomplishing that we can't do through Styling?

Get Outlook for iOS




On Mon, Dec 5, 2016 at 4:52 PM -0600, "James Spence" <notifications@github.com> wrote:












We do all the calculations within the card so we can specify a single prop on the card, size, that determines if it's full or half size. I assume these cards will not be many other sizes, so I put that within the class itself. Please check out the implementation, I can add some JSDoc to help clarify as well.

**Comment by jamesaspence** [comment]
Because otherwise, every time we bring in that card, we have to specify that styling. That means every time we want a card that is half width, we need to specify all the stylings to make it so. This makes it very easy to toggle it on / off. We could add another flag for custom styling, that just specifies everything but width / height in order to let the user override.

**Comment by theosyslack** [comment]
I'll move the card styles into the style folder in Sprint 3.

**Pull request merged**
