### PR TITLE
Code Review Changes

### PR DESCRIPTION
**Pull request by theosyslack**

### CODE REVIEW

**Comment by jamesaspence** [comment]
Changed the base to develop instead of master - we'll create a release branch when it is time.

**Review by jamesaspence — CHANGES_REQUESTED** [review]
Shouldn't this example use `fadein.getParallel().start();` instead of directly accessing the prop?

**Comment by jamesaspence** [comment]
Otherwise, looks good, if you have some time please add some documentation onto the methods (other than the accessors, no docs needed there)

**Comment by theosyslack** [comment]
If you check out commit `5c800aa0`, you can see everything before I added in the accessors. Now, I'm getting all sorts of errors I don't know how to debug. Even if I use the new accessor, it seems like  Animated doesn't like the way we have these accessors implemented. Is it because it's returning a value instead of an instance? Not really sure.

**Comment by jamesaspence** [comment]
I will take a look when I get home tonight, see if I can figure out what the issue is.

**Comment by jamesaspence** [comment]
If you want to push up your changes, I will take a look and see if it's reproducible on my end too

**Pull request merged**
