### PR TITLE
Feature/unit testing

### PR DESCRIPTION
**Pull request by jamesaspence**

### CODE REVIEW

**Review by theosyslack — COMMENTED** [review]
Looks good! All for more test coverage.

To me, TestCase seems like it's a utility class, not a test case or test case factory. Am I reading that wrong or should it be renamed?

**Comment by jamesaspence** [comment]
That is correct, that is a utility class. I can rename it if need be

**Comment by theosyslack** [comment]
Yeah, I'd say rename it. Better to clear it up now rather than later. Everything is spot on, tough. Good coverage of the child rendering stuff, I probably wouldn't have thought to do that.

**Comment by jamesaspence** [comment]
I'm not sure what naming convention to use for that. I used TestCase in my unit testing in PHP as well

**Review by theosyslack — APPROVED** [review]

**Pull request merged**
